-- vim commands
vim.cmd("set number")
vim.cmd("set relativenumber")
vim.cmd("set nowrap")
vim.cmd("set ts=4 sw=4")
vim.cmd("set autoindent")
vim.cmd("set mouse=")
vim.cmd("let g:nord_bold = v:false")
vim.cmd("autocmd filetype c nnoremap <C-c> :!gcc -o  %:r % -Wall -pedantic-errors -Werror<Enter>")
vim.cmd("autocmd filetype cpp nnoremap <C-c> :!g++ -o  %:r % -pedantic-errors -Werror<Enter>")
vim.cmd("autocmd filetype asm nnoremap <C-c> :!nasm -f elf32 % -o %:r.o<Enter>")
vim.cmd("autocmd filetype asm nnoremap <C-l> :!ld -m elf_i386 %:r.o -o %:r ")
vim.cmd("autocmd filetype java nnoremap <C-c> :!javac %<Enter>")
vim.cmd("autocmd filetype java nnoremap <C-x> :term java Main")
vim.cmd("autocmd filetype rust nnoremap <C-c> :!rustc %<Enter>")
vim.cmd("nnoremap <C-x> :term %:p:r")
vim.cmd("nnoremap <F5> :term python3 %<Enter>")
vim.cmd("autocmd filetype sh nnoremap <F3> :term %<Enter>")
vim.cmd("autocmd filetype sh nnoremap <F2> :! chmod +x %<Enter>")
vim.cmd('nnoremap <C-p> "+p')
vim.cmd('vnoremap <C-y> "+y')
-- Move between panes/splits directly from the OpenCode terminal
vim.keymap.set({'t', 'n'}, '<A-h>', [[<C-\><C-n><C-w>h]], { desc = "Move left from terminal" })
vim.keymap.set({'t', 'n'}, '<A-j>', [[<C-\><C-n><C-w>j]], { desc = "Move down from terminal" })
vim.keymap.set({'t', 'n'}, '<A-k>', [[<C-\><C-n><C-w>k]], { desc = "Move up from terminal" })
vim.keymap.set({'t', 'n'}, '<A-l>', [[<C-\><C-n><C-w>l]], { desc = "Move right from terminal" })
vim.g.mapleader = " "
